/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EntropySwapERC7984ToERC7984Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "depositTokenA"
      | "depositTokenB"
      | "entropyOracle"
      | "getEncryptedBalance"
      | "getEntropyOracle"
      | "requestSwapWithEntropy"
      | "swapAToBWithEntropy"
      | "swapRequestCount"
      | "swapRequests"
      | "tokenA"
      | "tokenB"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SwapRequested" | "Swapped"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositTokenA",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTokenB",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestSwapWithEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAToBWithEntropy",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tokenA", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenB", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositTokenA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositTokenB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSwapWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAToBWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenB", data: BytesLike): Result;
}

export namespace SwapRequestedEvent {
  export type InputTuple = [user: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [user: string, requestId: bigint];
  export interface OutputObject {
    user: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwappedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    encryptedAmountIn: BytesLike,
    encryptedAmountOut: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    tokenIn: string,
    tokenOut: string,
    encryptedAmountIn: string,
    encryptedAmountOut: string
  ];
  export interface OutputObject {
    user: string;
    tokenIn: string;
    tokenOut: string;
    encryptedAmountIn: string;
    encryptedAmountOut: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropySwapERC7984ToERC7984 extends BaseContract {
  connect(runner?: ContractRunner | null): EntropySwapERC7984ToERC7984;
  waitForDeployment(): Promise<this>;

  interface: EntropySwapERC7984ToERC7984Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  depositTokenA: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  depositTokenB: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  getEncryptedBalance: TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [string],
    "view"
  >;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  requestSwapWithEntropy: TypedContractMethod<
    [tag: BytesLike],
    [bigint],
    "payable"
  >;

  swapAToBWithEntropy: TypedContractMethod<
    [
      requestId: BigNumberish,
      encryptedAmountIn: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  swapRequestCount: TypedContractMethod<[], [bigint], "view">;

  swapRequests: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  tokenA: TypedContractMethod<[], [string], "view">;

  tokenB: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositTokenA"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositTokenB"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestSwapWithEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "swapAToBWithEntropy"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      encryptedAmountIn: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tokenA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenB"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "SwapRequested"
  ): TypedContractEvent<
    SwapRequestedEvent.InputTuple,
    SwapRequestedEvent.OutputTuple,
    SwapRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Swapped"
  ): TypedContractEvent<
    SwappedEvent.InputTuple,
    SwappedEvent.OutputTuple,
    SwappedEvent.OutputObject
  >;

  filters: {
    "SwapRequested(address,uint256)": TypedContractEvent<
      SwapRequestedEvent.InputTuple,
      SwapRequestedEvent.OutputTuple,
      SwapRequestedEvent.OutputObject
    >;
    SwapRequested: TypedContractEvent<
      SwapRequestedEvent.InputTuple,
      SwapRequestedEvent.OutputTuple,
      SwapRequestedEvent.OutputObject
    >;

    "Swapped(address,address,address,bytes,bytes)": TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
    Swapped: TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
  };
}
